import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{invoke,isTauri}from'@tauri-apps/api/core';
import{Boxes,Search,RefreshCw,Settings as SettingsIcon,Store,History,ArrowUpRight,ShieldCheck,X,Plus,Folder,AlertTriangle,ChevronRight}from'lucide-react';
import{Component,Inventory,Settings,Plan,Operation,MarketResult,labels,filterComponents}from'./types';
import'./style.css';
import { InventoryExport } from './InventoryExport';
import { RecoveryPanel } from './RecoveryPanel';
import { ComponentActions } from './ComponentActions';
import { BindingDetails, BindingSummary } from './BindingDetails';
import { InventoryFilters } from './InventoryFilters';
import { operationFeedback, type Capabilities } from './types';
import { MarketDetail } from './MarketDetail';
import type { MarketItem } from './types';
import { ChangePreview } from './ChangePreview';
import { ComponentEditor, type EditorSession, type EditRequest } from './ComponentEditor';
const empty:Inventory={components:[],issues:[],scannedAt:0};
export function App(){
 const[page,setPage]=useState('inventory'),[data,setData]=useState(empty),[settings,setSettings]=useState<Settings>({home:'',projects:[]}),[query,setQuery]=useState(''),[kind,setKind]=useState('all'),[agent,setAgent]=useState('all'),[selected,setSelected]=useState<Component|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[plan,setPlan]=useState<Plan|null>(null),[market,setMarket]=useState<MarketResult|null>(null),[source,setSource]=useState('GitHub'),[history,setHistory]=useState<Operation[]>([]),[editor,setEditor]=useState<EditorSession|null>(null);
 const [scope,setScope]=useState('all'),[status,setStatus]=useState('all');
 const desktop=isTauri();
 const [capabilities,setCapabilities]=useState<Capabilities|null>(null);
 const [marketDetail,setMarketDetail]=useState<MarketItem|null>(null);
 async function perform(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{if(!desktop)throw new Error('浏览器仅展示界面。请使用 npm run tauri dev 启动桌面应用，访问真实本机组件。');await fn()}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function refresh(){setSelected(null);setPlan(null);setEditor(null);setData(await invoke<Inventory>('scan'))}
 useEffect(()=>{if(desktop)void perform(async()=>{const[s,d,c]=await Promise.all([invoke<Settings>('settings'),invoke<Inventory>('inventory'),invoke<Capabilities>('capabilities')]);setSettings(s);setData(d);setCapabilities(c)})},[]);
 async function preview(a:string,c:Component){await perform(async()=>{const p=await invoke<Plan>(c.kind==='mcp'?'preview_mcp':'preview',{action:a,id:c.id,name:c.name,content:'',agent:c.agent});setPlan(p)})}
 function openInstall(kind:'skill'|'mcp',suggestedName='',seed?:string){setSelected(null);setEditor({action:'install',component:null,kind,name:suggestedName,content:kind==='mcp'?(seed??'{}'):'---\nname: my-skill\ndescription: 描述此 Skill 的用途\n---\n\n'})}
 async function openUpdate(c:Component){await perform(async()=>{const content=c.kind==='skill'?await invoke<string>('read_skill',{id:c.id}):'{}';setEditor({action:'update',component:c,kind:c.kind==='mcp'?'mcp':'skill',content})})}
 async function previewEditor(request:EditRequest){if(!editor)return;await perform(async()=>{const command=request.mode==='package'?'preview_package':request.mode==='mcp'?'preview_mcp':'preview';const p=await invoke<Plan>(command,{action:editor.action,id:editor.component?.id??null,...request});setPlan(p);setEditor(null)})}
 async function applyPlan(id:string){await perform(async()=>{
   const op=await invoke<Operation>('apply_plan',{id,confirmed:true});
   setPlan(null);setSelected(null);setHistory(previous=>[op,...previous.filter(item=>item.id!==op.id)]);
   const feedback=operationFeedback(op);
   const updates=await Promise.allSettled([invoke<Operation[]>('history'),invoke<Inventory>('inventory')]);
   if(updates[0].status==='fulfilled')setHistory(updates[0].value);
   if(updates[1].status==='fulfilled')setData(updates[1].value);
   const refreshWarning=updates.some(result=>result.status==='rejected')?' 清单或记录刷新失败，请重新扫描并检查操作记录。':'';
   if(feedback.level==='error')throw new Error(feedback.message+refreshWarning);
   setNotice((feedback.level==='warning'?'已应用，但需处理后续问题：':'')+feedback.message+refreshWarning);
 })}
 const items=filterComponents(data.components,query,kind,agent,scope,status);
 const counts={skills:data.components.filter(c=>c.kind==='skill').length,mcp:data.components.filter(c=>c.kind==='mcp').length,plugin:data.components.filter(c=>c.kind==='plugin').length,issues:data.components.filter(c=>c.status.some(s=>s==='duplicate'||s==='conflict')).length};
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-icon"><Boxes size={23}/></div><div>Agent Components<small>本机组件控制中心</small></div></div><div className="nav-label">工作空间</div>{[['inventory','本机组件',Boxes],['market','发现市场',Store],['history','操作记录',History],['settings','设置',SettingsIcon]].map(([id,title,Icon])=><button key={String(id)} className={`nav ${page===id?'active':''}`} onClick={()=>{setPage(String(id));if(id==='history')void perform(async()=>setHistory(await invoke<Operation[]>('history')))}}><Icon size={18}/>{String(title)}{page===id&&<span className="nav-dot"/>}</button>)}<div className="local-note"><ShieldCheck size={19}/><strong>本地优先，操作可追溯</strong><p>先预览，再确认。变更前自动备份，不执行第三方脚本。</p><span className="version">WINDOWS · 开发预览</span></div></aside>
 <main><header><div className="breadcrumb">工作空间 <ChevronRight size={13}/> {({inventory:'本机组件',market:'发现市场',history:'操作记录',settings:'设置'} as Record<string,string>)[page]}</div><span className="connection"><i/>{desktop?'本地桌面环境':'界面预览 · 未连接本机'}</span></header><div className="content">
 <div className="page-heading"><div><div className="eyebrow">YOUR AGENT TOOLBOX</div><h1>{({inventory:'管理你的 Agent 组件',market:'发现下一件好工具',history:'每一次变更，都有记录',settings:'连接你的工作环境'}as Record<string,string>)[page]}</h1><p>{page==='inventory'?'看清装了什么、在哪里、被谁使用。让散落的工具井然有序。':page==='market'?'从可信来源发现组件。热度不代表安全，安装前请审阅内容。':page==='settings'?'扫描范围由你掌控。设置保存在本机。':'查看执行结果和错误信息，备份保存在应用数据目录。'}</p></div>{page==='inventory'&&<button className="primary" disabled={busy} onClick={()=>void perform(refresh)}><RefreshCw size={16} className={busy?'spin':''}/>{busy?'正在扫描…':'扫描本机'}</button>}</div>
 {!desktop&&<div className="banner">这是界面预览，没有模拟的安装数据。桌面模式下可扫描 Codex、Claude Code 和共享 Skill 目录。</div>}{error&&<div role="alert" className="banner error">{error}</div>}{notice&&<div role="status" className="banner">{notice}</div>}
 {page==='inventory'&&<><div className="stats">{[['Skills',counts.skills,'可复用的指令与能力'],['MCP Servers',counts.mcp,'Agent 的外部连接'],['Plugins',counts.plugin,'已发现的扩展包'],['需要留意',counts.issues,'重复内容与同名差异']].map(([title,count,desc])=><div className="stat" key={title}><span>{title}</span><strong>{count}</strong><small>{desc}</small></div>)}</div><section className="panel"><div className="panel-title"><h2>组件清单 <span>{data.components.length}</span></h2><div className="actions"><InventoryExport desktop={desktop} scannedAt={data.scannedAt} home={settings.home} busy={busy}/><button onClick={()=>openInstall('skill')}><Plus size={15}/>安装 Skill</button><button onClick={()=>openInstall('mcp')}><Plus size={15}/>添加 MCP</button></div></div><div className="filters"><label className="search"><Search size={17}/><input aria-label="搜索组件" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索名称、描述或路径…"/></label><select aria-label="组件类型" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">所有类型</option><option value="skill">Skill</option><option value="mcp">MCP</option><option value="plugin">Plugin</option></select><select aria-label="所属 Agent" value={agent} onChange={e=>setAgent(e.target.value)}><option value="all">所有 Agent</option><option>Codex</option><option>Claude Code</option><option>Shared</option></select><InventoryFilters scope={scope} status={status} onScope={setScope} onStatus={setStatus}/></div>{items.length?<div className="table-wrap"><table><thead><tr><th>组件</th><th>Agent / 范围</th><th>观察状态</th><th>检查结果</th><th/></tr></thead><tbody>{items.map(c=><tr key={c.id} onClick={()=>setSelected(c)}><td><div className={`type-icon ${c.kind}`}>{c.kind==='skill'?'S':c.kind==='mcp'?'M':'P'}</div><div className="component-name"><button className="link" onClick={()=>setSelected(c)}>{c.name}</button><small>{c.description||'暂无描述'}</small></div></td><td>{c.agent}<small>{labels[c.scope]??c.scope}</small><BindingSummary component={c} components={data.components}/></td><td><span className="badge">{labels[c.effective]??c.effective}</span></td><td>{c.status.length?c.status.map(s=><span key={s} className={`badge ${s}`}>{labels[s]??s}</span>):<span className="muted">—</span>}</td><td><ChevronRight size={16}/></td></tr>)}</tbody></table></div>:<div className="empty"><Folder size={40}/><h3>{data.scannedAt?'没有匹配的组件':'先认识一下你的工具箱'}</h3><p>{data.scannedAt?'调整筛选条件，或在设置中添加项目路径。':'点击「扫描本机」，建立第一份本地清单。'}</p></div>}<div className="panel-footer">{data.scannedAt?`上次扫描 ${new Date(data.scannedAt*1000).toLocaleString()}`:'尚未扫描'}<span>发现 ≠ 已加载 · 不展示 MCP 凭据</span></div></section>{data.issues.length>0&&<section className="panel issues"><h2><AlertTriangle size={18}/>扫描问题 · {data.issues.length}</h2>{data.issues.map((i,n)=><details key={n}><summary>{i.path}</summary><p>{i.message}</p></details>)}</section>}</>}
 {page==='market'&&<><div className="filters panel"><select value={source} onChange={e=>setSource(e.target.value)}><option>GitHub</option><option>MCP Registry</option><option>Claude Marketplace</option></select><label className="search"><Search size={18}/><input aria-label="搜索市场" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索技能、服务器或插件…" onKeyDown={e=>{if(e.key==='Enter')void perform(async()=>setMarket(await invoke('market',{source,query})))}}/></label><button disabled={busy} className="primary" onClick={()=>void perform(async()=>setMarket(await invoke('market',{source,query})))}>搜索</button></div>{market&&market.items.length===0&&<div className="empty"><h3>没有找到匹配结果</h3><p>尝试其他关键词或来源。</p></div>}{market?.stale&&<div className="banner">正在显示缓存结果：{market.message}</div>}<div className="market-grid">{market?.items.map((m,i)=><article className="panel market-card" key={i}><span className="eyebrow">{m.source}</span><h2>{m.name}</h2><p>{m.description||'来源未提供描述'}</p><div className="market-meta">{m.stars!==null?`★ ${m.stars.toLocaleString()} · GitHub`:'热度数据未提供'}{m.version&&` · v${m.version}`}</div><small>获取于 {new Date(m.fetchedAt*1000).toLocaleString()}</small><a href={/^https:\/\//.test(m.url)?m.url:undefined} target="_blank" rel="noreferrer">查看来源 <ArrowUpRight size={15}/></a><button disabled={busy} onClick={()=>setMarketDetail(m)}>查看详情与安装方式</button></article>)}</div>{!market&&<div className="empty"><Store size={40}/><h3>连接三个来源，保留各自出处</h3><p>GitHub 仓库 · 官方 MCP Registry · Claude 官方插件目录</p></div>}</>}
 {page==='settings'&&<section className="panel settings"><h2>扫描范围</h2><label>用户主目录<input value={settings.home} onChange={e=>setSettings({...settings,home:e.target.value})}/></label><label>Codex 目录（可选）<input value={settings.codexHome??''} placeholder="CODEX_HOME / .codex" onChange={e=>setSettings({...settings,codexHome:e.target.value})}/></label><label>Claude Code 目录（可选）<input value={settings.claudeHome??''} placeholder=".claude" onChange={e=>setSettings({...settings,claudeHome:e.target.value})}/></label><label>项目目录（每行一个绝对路径）<textarea rows={6} value={settings.projects.join('\n')} onChange={e=>setSettings({...settings,projects:e.target.value.split('\n')})}/></label><p>自定义目录优先。留空时 Codex 使用 CODEX_HOME 或用户主目录下的 .codex；Claude Code 使用 .claude。Claude 用户 MCP 配置仍来自用户主目录下的 .claude.json。共享 Skill 来自 .agents/skills。</p><button className="primary" disabled={busy} onClick={()=>void perform(async()=>{const value={...settings,codexHome:settings.codexHome?.trim()||null,claudeHome:settings.claudeHome?.trim()||null,projects:settings.projects.map(p=>p.trim()).filter(Boolean)};await invoke('save_settings',{value});setSettings(value);setData(empty);setSelected(null);setPlan(null);setNotice('设置已保存。重新扫描后生效。')})}>保存设置</button></section>}
 {page==='history'&&desktop&&<RecoveryPanel enabled={capabilities?.mutationsEnabled===true} onRecovered={async()=>{setSelected(null);setPlan(null);setEditor(null);setHistory(await invoke<Operation[]>('history'));setData(await invoke<Inventory>('inventory'));}}/>}
 {page==='history'&&<section className="panel">{history.length?history.map(o=><div className="history-row" key={o.id}><span className={`badge ${operationFeedback(o).level!=='success'?'conflict':''}`}>{({completed:'已完成',completed_with_warning:'已完成 · 有警告',completed_with_warnings:'已完成 · 有警告',failed:'失败',started:'已开始'} as Record<string,string>)[o.status]??o.status}</span><div><strong>{o.title}</strong><p>{o.message}</p><small>{new Date(o.at*1000).toLocaleString()}</small></div></div>):<div className="empty"><History size={40}/><h3>还没有变更记录</h3><p>所有操作都需要先预览并明确确认。</p></div>}</section>}
 </div></main>
 {selected&&!editor&&!plan&&<div className="overlay" onClick={()=>setSelected(null)}><section className="drawer" onClick={e=>e.stopPropagation()}><button className="close" aria-label="关闭详情" onClick={()=>setSelected(null)}><X/></button><span className="eyebrow">{selected.kind.toUpperCase()} / {selected.agent}</span><h2>{selected.name}</h2><p>{selected.description}</p><BindingDetails component={selected} components={data.components}/><dl>{[['观察状态',labels[selected.effective]??selected.effective],['位置',selected.path],['实际位置',selected.canonicalPath],['内容 SHA-256',selected.hash],['版本',selected.version??'未提供']].map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{v}</dd></React.Fragment>)}</dl><div className="banner">清单记录文件与配置状态，不代表 Agent 已在当前会话加载。</div><ComponentActions component={selected} busy={busy} onUpdate={()=>void openUpdate(selected)} onPreview={action=>void preview(action,selected)} onPluginPreview={(action,name,scope)=>void perform(async()=>setPlan(await invoke<Plan>('preview_plugin',{action,name,scope})))}/></section></div>}
 {marketDetail&&<MarketDetail key={marketDetail.source+marketDetail.name} item={marketDetail} busy={busy} error={error} onClose={()=>setMarketDetail(null)} onMcp={content=>{setMarketDetail(null);openInstall('mcp','',content)}} onPreview={(command,args)=>void perform(async()=>{const p=await invoke<Plan>(command,args);setMarketDetail(null);setPlan(p)})}/>}
 {editor&&<ComponentEditor projects={settings.projects} session={editor} busy={busy} error={error} onClose={()=>setEditor(null)} onPreview={r=>void previewEditor(r)}/>}
 {plan&&<ChangePreview key={plan.id} plan={plan} enabled={capabilities?.mutationsEnabled===true} busy={busy} error={error} onClose={()=>setPlan(null)} onApply={applyPlan}/>}

 </div>
}
const root = document.getElementById('root');
if(root) createRoot(root).render(<App/>);
